name: Build APK

on:
  push:
    branches: [ master ]        # 仅 master 更新时触发
  workflow_dispatch:            # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (含子模块)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew :app_main:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RFIDtools-latest
          path: app_main/build/outputs/apk/release/app_main-release.apk
