name: Build RFIDtools APK

on:
  push:
    branches: [ master ]   # 推送到 master 就触发；如用 main 请改名
  workflow_dispatch:       # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build release APK
        run: ./gradlew :app_main:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RFIDtools-release
          path: app_main/build/outputs/apk/release/app_main-release.apk
